name: growvy_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  
  # Firebase
  intl: ^0.20.2 
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  http: ^1.5.0
  google_sign_in: ^6.1.4
  firebase_ui_oauth_google: ^1.4.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
  
  fonts:
  - family: Pretendard
    fonts:
      - asset: assets/font/Pretendard-Thin.ttf
        weight: 100
      - asset: assets/font/Pretendard-ExtraLight.ttf
        weight: 200
      - asset: assets/font/Pretendard-Light.ttf
        weight: 300
      - asset: assets/font/Pretendard-Regular.ttf
        weight: 400
      - asset: assets/font/Pretendard-Medium.ttf
        weight: 500
      - asset: assets/font/Pretendard-SemiBold.ttf
        weight: 600
      - asset: assets/font/Pretendard-Bold.ttf
        weight: 700
      - asset: assets/font/Pretendard-ExtraBold.ttf
        weight: 800
      - asset: assets/font/Pretendard-Black.ttf
        weight: 900
